models.py
from flask_login import UserMixin
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from app import db


class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False, unique=True)
    password = db.Column(db.String(80), nullable=False)


class RegisterForm(FlaskForm):
    username = StringField(validators=[
        InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username", "class": "form-control"})

    password = PasswordField(validators=[
        InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password", "class": "form-control"})

    submit = SubmitField('Register', render_kw={"class":"btn btn-primary"})

    def validate_username(self, username):
        existing_user_username = Users.query.filter_by(
            username=username.data).first()
        if existing_user_username:
            raise ValidationError(
                'That username already exists. Please choose a different one.')


class LoginForm(FlaskForm):
    username = StringField(validators=[
        InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username", "class": "form-control"})

    password = PasswordField(validators=[
        InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password", "class": "form-control"})

    submit = SubmitField('Login', render_kw={"class":"btn btn-primary"})

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from flask_bcrypt import Bcrypt

db = SQLAlchemy()
bcrypt = Bcrypt()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '0eeff27f9c89ab975e01c1eb5aeef5148b1810e9b690a77bedd94a261b3d9b98'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://flask:Passw0rd!@postgres:5432/flask'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
    bcrypt.init_app(app)

    from views import views
    from auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from models import Users

    # create_database(app)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'

    @login_manager.user_loader
    def load_user(user_id):
        return Users.query.get(int(user_id))

    return app


def create_database(app):
    if not path.exists(DB_NAME):
        db.create_all(app=app)
        print('Created Database!')


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

auth.py
from flask import Blueprint, render_template, redirect, url_for
from models import Users, LoginForm, RegisterForm
from app import db, bcrypt
from flask_login import login_user, login_required, logout_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('views.success'))
    return render_template('login.html', form=form)


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf8')
        new_user = Users(username=form.username.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('auth.login'))

    return render_template('register.html', form=form)

views.py
from flask import Blueprint, render_template
from flask_login import login_required

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('home.html')


@views.route('/success', methods=['GET', 'POST'])
@login_required
def success():
    return render_template('success.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <h1>Login Authentication System in Flask.</h1>
    <a href="{{ url_for('auth.login') }}">Login Page</a><br>
    <a href="{{ url_for('auth.register') }}">Register Page</a><br>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login Page{% endblock %}
{% block content %}
<h1>Login Page</h1>

<form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.username }}
    </div>
    <div class="mb-3">
        {{ form.password }}
    </div>
    {{ form.submit }}
</form>

<div class="mt-3"></div>
<a class="btn-link" href="{{ url_for('auth.register') }}">Don't have an account? Register here</a>
<div class="mt-3"></div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}Register Page{% endblock %}
{% block content %}
<h1>Register Page</h1>

<form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.username }}
    </div>
    <div class="mb-3">
        {{ form.password }}
    </div>
    {{ form.submit }}
</form>

<div class="mt-3">
    <a class="btn-link" href="{{ url_for('auth.login') }}">Already have an account? Log In</a>
</div>
{% endblock %}

templates/success.html
{% extends "base.html" %}
{% block title %}Success Page{% endblock %}
{% block content %}
<img src="{{ url_for('static', filename='uareamazing.jpg') }}" class="img-fluid" alt="uareamazing.jpg">
<div class="mt-3"></div>
<a href="{{ url_for('auth.logout') }}">Press here to logout</a>
</div>
{% endblock %}